// SPDX-License-Identifier: Apache-2.0

import { join } from 'node:path';
import { writeFile, ensureDir, fileExists } from '../lib/filesystem.js';
import { loadTemplate } from '../lib/templates.js';

const SYSTEM_YAML = `# Owned System Record
# Generated by osk init
# See: https://github.com/Beach-Bum/owned-systems-kit

name: ""
version: "0.1.0"
description: ""
owner: ""
created: "${new Date().toISOString().split('T')[0]}"
last_reviewed: "${new Date().toISOString().split('T')[0]}"

# AI providers and models in use
providers: []

# Primary workflows documented in this package
workflows: []

# Human review gates defined
review_gates: []

# Evidence chain logging enabled
evidence_chain:
  enabled: true
  format: "markdown"
  location: "evidence/"
`;

const DOC_FILES = [
  '00-overview.md',
  '01-workflow-map.md',
  '02-tools-and-dependencies.md',
  '03-data-boundaries.md',
  '04-prompts-and-templates.md',
  '05-human-review-gates.md',
  '06-evaluation-checklist.md',
  '07-runbook.md',
  '08-maintenance.md',
  '09-exit-plan.md',
];

export async function init(_args: string[]): Promise<void> {
  const cwd = process.cwd();

  if (fileExists(join(cwd, 'owned-system.yaml'))) {
    console.error('owned-system.yaml already exists. Aborting.');
    process.exit(1);
  }

  console.log('Scaffolding owned system documentation package...\n');

  // Write owned-system.yaml
  writeFile(join(cwd, 'owned-system.yaml'), SYSTEM_YAML);
  console.log('  owned-system.yaml');

  // Create directories
  ensureDir(join(cwd, 'docs'));
  ensureDir(join(cwd, 'evidence'));
  ensureDir(join(cwd, 'workflows'));
  ensureDir(join(cwd, 'gates'));

  // Write .gitkeep files for empty directories
  writeFile(join(cwd, 'evidence', '.gitkeep'), '');
  writeFile(join(cwd, 'workflows', '.gitkeep'), '');
  writeFile(join(cwd, 'gates', '.gitkeep'), '');

  // Write documentation templates
  for (const file of DOC_FILES) {
    let content: string;
    try {
      content = loadTemplate(file);
    } catch {
      // Fallback if template not found
      const title = file.replace(/^\d+-/, '').replace(/\.md$/, '').replace(/-/g, ' ');
      content = `# ${title.charAt(0).toUpperCase() + title.slice(1)}\n\nTODO: Fill in this section.\n`;
    }
    writeFile(join(cwd, 'docs', file), content);
    console.log(`  docs/${file}`);
  }

  console.log('  evidence/.gitkeep');
  console.log('  workflows/.gitkeep');
  console.log('  gates/.gitkeep');

  console.log('\nDone. Edit owned-system.yaml and fill in the docs/ templates.');
  console.log('Run "osk check" to validate your documentation package.');
}
